#!/bin/bash

#   +-+-+ +-+-+-+-+-+-+-+-+-+-+-+-+  
#   +-+-+ +-+-+-+-+-+-+-+-+-+-+-+-+  
#   |B|Y| |-|-|>|.|a|m|i|n|e|l|c|h|  
#   +-+-+ +-+-+-+-+-+-+-+-+-+-+-+-+  
#   +-+-+ +-+-+-+-+-+-+-+-+-+-+-+-+  

 


# Some useful git aliases 

alias gs='git status '

alias ga='git add '

alias gb='git branch '

alias gc='git commit'

alias gd='git diff'

alias gco='git checkout '

alias glg='git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative'