#!/bin/bash

#   +-+-+ +-+-+-+-+-+-+-+-+-+-+-+-+  
#   +-+-+ +-+-+-+-+-+-+-+-+-+-+-+-+  
#   |B|Y| |-|-|>|.|a|m|i|n|e|l|c|h|  
#   +-+-+ +-+-+-+-+-+-+-+-+-+-+-+-+  
#   +-+-+ +-+-+-+-+-+-+-+-+-+-+-+-+  

 


# Allow aliases to be with sudo
alias sudo="sudo "

# Easier navigation: .., ..., ~ and -
alias ee="exit"
alias z="cd"
alias ..="cd .."

# My working directory 
alias pfe="cd ~/PFE"
alias PFE="cd ~/PFE"

# Aliases to diplay some colorls commands 
alias lc='colorls -lA --sd'
alias ll='colorls --gs'
alias la='colorls -r'

# Clear terminal 
alias c="clear"

# Copy selection to clipboard
alias cc='xclip -selection clipboard'

# Open .zshrc file on nano 
alias zshconfig="nano ~/.zshrc"

# Source .zshrc file 
alias zshupdate="source ~/.zshrc"

# Generate a random password 
alias getpass="openssl rand -base64 20"

# Copy mygit password to clipboard
alias gitpass="cat ~/Documents/git.txt|cc"

# Open new url on firefox
alias sudo="firefox --new-tab << `read;echo $url` "

# What is my ip 
alias myip="echo your IP adress is : `curl ipinfo.io/ip`"

# Open PHP built in server 
alias phps="php -S localhost:8000 -ddisplay_errors=1"

# Open Angular built in server
alias ngs='ng serve'

# Alias to taskbook utility 
alias tb ='taskbook'

# Run kickthemout script 
alias kick="sudo python3 ~/kickthemout/kickthemout.py"

# Just update system
alias update='sudo apt-get update'

# Update & upgrade packages to latest version
alias update='sudo apt-get update && sudo apt-get upgrade'

# Alias to symfony console
alias sc="symfony console"

# Devdocs alias 
alias devdoc="cd ~/githubProjects/devdocs; bundle exec rackup"

# Youtube-dl 
yt="youtube-dl --add-metadata -i"  #download audio/video file 
yta="yt -x -f bestaudio/best" #download only sound's video

# Copy mysql credentials to clipboard 
mysqlpass='xclip -sel cli < ~/Documents/mysql.pass'
alias connectdb="mysql -u root"
